name: 🚀 Upload to Cloudflare R2
on:
  release:
    types: [published]

jobs:
  published:
    runs-on: ubuntu-latest
    steps:
      - name: Download Release Assets
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          regex: true
          file: '/*'
          target: 'plugin-updates/' # 下载到的目标目录
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload to Cloudflare R2
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: ./plugin-updates
          destination-dir: ./plugin-updates
